-- Health Snapshots Table
-- Daily AI-generated health summaries combining wearables, training, and nutrition data

CREATE TABLE IF NOT EXISTS health_snapshots (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,

  -- Wearable Metrics
  sleep_duration_hours DECIMAL(4,2),
  sleep_quality_score INTEGER CHECK (sleep_quality_score >= 0 AND sleep_quality_score <= 100),
  hrv_score INTEGER, -- milliseconds
  resting_heart_rate INTEGER, -- bpm
  recovery_score INTEGER CHECK (recovery_score >= 0 AND recovery_score <= 100),

  -- Training Metrics
  training_volume_minutes INTEGER,
  training_intensity_score INTEGER CHECK (training_intensity_score >= 0 AND training_intensity_score <= 100),
  adherence_percentage DECIMAL(5,2),
  workouts_completed INTEGER,
  workouts_scheduled INTEGER,

  -- Nutrition Metrics
  calories_consumed INTEGER,
  protein_grams DECIMAL(6,2),
  carbs_grams DECIMAL(6,2),
  fats_grams DECIMAL(6,2),
  hydration_liters DECIMAL(4,2),

  -- Subjective Metrics
  readiness_score INTEGER CHECK (readiness_score >= 1 AND readiness_score <= 5),
  soreness_level INTEGER CHECK (soreness_level >= 1 AND soreness_level <= 5),
  mood_score INTEGER CHECK (mood_score >= 1 AND mood_score <= 5),

  -- AI-Generated Insights
  ai_summary TEXT,
  ai_recommendations JSONB DEFAULT '[]'::jsonb,
  risk_flags JSONB DEFAULT '[]'::jsonb,

  -- Metadata
  data_completeness_score INTEGER CHECK (data_completeness_score >= 0 AND data_completeness_score <= 100),
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  UNIQUE(user_id, date)
);

-- Indexes
CREATE INDEX idx_health_snapshots_user_date ON health_snapshots(user_id, date DESC);
CREATE INDEX idx_health_snapshots_generated ON health_snapshots(generated_at DESC);
CREATE INDEX idx_health_snapshots_completeness ON health_snapshots(data_completeness_score DESC);

-- RLS Policies
ALTER TABLE health_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own snapshots"
  ON health_snapshots FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own snapshots"
  ON health_snapshots FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own snapshots"
  ON health_snapshots FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Coaches can view client snapshots"
  ON health_snapshots FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM client_assignments
      WHERE client_id = health_snapshots.user_id
      AND coach_id = auth.uid()
      AND status = 'active'
    )
  );

-- Updated_at trigger
CREATE TRIGGER update_health_snapshots_updated_at
  BEFORE UPDATE ON health_snapshots
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE health_snapshots IS 'Daily AI-generated health summaries combining wearables, training, and nutrition data';
COMMENT ON COLUMN health_snapshots.sleep_quality_score IS 'Sleep quality score from 0-100';
COMMENT ON COLUMN health_snapshots.recovery_score IS 'Recovery score from 0-100 (Whoop/Oura style)';
COMMENT ON COLUMN health_snapshots.training_intensity_score IS 'Training intensity score from 0-100';
COMMENT ON COLUMN health_snapshots.adherence_percentage IS 'Percentage of scheduled workouts completed';
COMMENT ON COLUMN health_snapshots.readiness_score IS 'User-reported readiness from 1-5';
COMMENT ON COLUMN health_snapshots.soreness_level IS 'User-reported soreness from 1-5';
COMMENT ON COLUMN health_snapshots.mood_score IS 'User-reported mood from 1-5';
COMMENT ON COLUMN health_snapshots.ai_summary IS 'Natural language summary generated by AI';
COMMENT ON COLUMN health_snapshots.ai_recommendations IS 'Array of AI-generated recommendations';
COMMENT ON COLUMN health_snapshots.risk_flags IS 'Array of risk indicators (overtraining, poor recovery, etc.)';
COMMENT ON COLUMN health_snapshots.data_completeness_score IS 'Score from 0-100 indicating how much data was available for analysis';
